customize the settings for the seeds via acre.yaml
gardener/garden-setup pull request #313
Opened 2020-10-09 19:41 UTC by hassbert

**What this PR does / why we need it**:
With the given changes you can modify the settings of the seeds via the `acre.yaml` in the `landscape.iaas` sections. We need to modify these settings to set our shoot api load balancers to internal.

**Which issue(s) this PR fixes**: none

**Special notes for your reviewer**:

**Release note**:
```improvement operator
modify seed settings via acre.yaml
```

2020-10-09 19:41 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/gardener/garden-setup?pullRequest=313) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/gardener/garden-setup?pullRequest=313) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/gardener/garden-setup?pullRequest=313) it.</sub>

2020-10-13 11:27 UTC, Diaphteiros requested changes
Looks good, I have only one smaller remark:

Since the acre.yaml file is already somewhat big and can get confusing, I would prefer the option to be named `seedSettings` (or something similar) there. If you look at the acre.yaml file and see `settings` somewhere there, it is not directly clear where these settings will end up, since the acre.yaml basically consists of 'settings'. 
If it is named `seedSettings`, on the first glance it becomes clear where these values belong to.

What do you think?

2020-10-13 11:34 UTC, hassbert commented
Makes perfectly sense to me. Will adapt your proposed change with the `seedSettings` name 👍

2020-10-13 12:04 UTC, Diaphteiros approved these changes
/lgtm

2020-10-13 12:05 UTC, Diaphteiros approved these changes

2020-10-13 12:06 UTC, merged