Packet Integration
gardener/garden-setup pull request #328
Opened 2020-10-30 09:52 UTC by gianarb

**What this PR does / why we need it**:

It adds support for [Packet](https://metal.equinix.com)

**Which issue(s) this PR fixes**:

There is not issue.

**Special notes for your reviewer**:

I don't know what I am doing

**Release note**:

```improvement operator
improvement user Add support for Packet
```

2020-10-30 09:52 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/gardener/garden-setup?pullRequest=328) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/gardener/garden-setup?pullRequest=328) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/gardener/garden-setup?pullRequest=328) it.</sub>

2020-10-30 11:46 UTC, Diaphteiros reviewed
I found one small copy-paste error, apart from that it looks good. I don't have packet credentials at hand to test it ...
Did you test it? You will have to choose a different DNS provider in your acre.yaml and deactivate the etcd backups for the virtual cluster etcd as well as for every seed (see here https://github.com/gardener/garden-setup/blob/master/docs/extended/iaas.md#seed-backup for the latter one). But all of that is configurable in your acre.yaml.

2020-10-30 11:46 UTC, Diaphteiros commented on dependency-versions.yaml
> +        "provider-openstack": {
copy-paste error: provider-packet

2020-12-16 14:23 UTC, Diaphteiros approved these changes
/lgtm

2020-12-16 14:28 UTC, Diaphteiros requested changes
Sorry, I somehow lost track of this PR. It looks good, I have just one minor request before I will merge it:
Please add the documentation for packet to the README.

2021-04-08 12:09 UTC, gianarb commented
I am not sure I have never got this code actually running. And it looks like the garden setup will be replaced by something else. So I am closing this for now

2021-04-08 12:10 UTC, closed without merging