Update Readme
gardener/garden-setup pull request #873
Opened 2022-08-17 19:31 UTC by jguipi

**What this PR does / why we need it**:
- Adding information on how to use a SA in the kubeconfig. It was not necessarily clear how to replace the basic authentication method.
 
**Which issue(s) this PR fixes**:
-
**Special notes for your reviewer**:

**Release note**:
```feature operator
- Adding information on how to use a SA in the kubeconfig. I
```

2022-08-18 06:25 UTC, Diaphteiros requested changes
Nice! Just fix the link and I'll merge it.

2022-08-18 06:25 UTC, Diaphteiros commented on README.md
> +    - If you are not using GKE and don't know how to get a kubeconfig with standard authentication, you can also create a serviceaccount, grant it cluster-admin privileges by adding it to the corresp
```suggestion
    - If you are not using GKE and don't know how to get a kubeconfig with standard authentication, you can also create a serviceaccount, grant it cluster-admin privileges by adding it to the corresponding `ClusterRoleBinding`, and construct a kubeconfig using that serviceaccount's token. [Look at an example here](README.md#adding-a-service-account-authentication-token-to-a-kubeconfig-file)
```

2022-08-18 19:12 UTC, jguipi commented on README.md
> +    - If you are not using GKE and don't know how to get a kubeconfig with standard authentication, you can also create a serviceaccount, grant it cluster-admin privileges by adding it to the corresp
Done :D

2022-08-18 19:12 UTC, jguipi commented
> Nice! Just fix the link and I'll merge it.

I updated it ! 
thx !

2022-08-31 14:17 UTC, jguipi commented
cc.: @Diaphteiros

2022-09-01 08:11 UTC, Diaphteiros approved these changes
/lgtm

2022-09-01 08:11 UTC, merged